---
- hosts: database
  sudo: yes
  roles: 
    - database

- hosts: cassandra-node
  sudo: yes
  roles: 
    - cassandra-base
    - cassandra-node

- hosts: cassandra-admin
  sudo: yes
  roles:
    - cassandra-base
