---
- name: Install packages
  hosts: manager
  sudo: yes
  tasks:
  - name: install base packages
    apt: name={{ item }} state=latest
    with_items: 
        - postgresql
        - php5-fpm
        - php5-pgsql
        - ntp
        - nginx
        - vim
        - python3-pip
        - python-pip
        - redis-server
        - monit

- name: Deploy the latest version of the configuration and code
  hosts: manager
  sudo: yes
  tasks:
  - name: sync config
    synchronize: src=config/scraper.ini dest=/usr/local/share/scraper.ini
    notify:
      - restart scraper
  - name: sync code
    synchronize: src=src/ dest=/usr/local/src/smisc/
    notify: 
      - restart scraper
  handlers:
    - name: restart scraper
      service: name=smisc-scraper state=restarted
