---
- name: install repository
  get_url: url=http://archive.zfsonlinux.org/debian/pool/main/z/zfsonlinux/zfsonlinux_4_all.deb dest=/tmp/zfsonlinux.deb
  tags:
    - zfs

- name: install zfsonlinux repository
  command: dpkg -i /tmp/zfsonlinux.deb
  tags:
    - zfs

- name: update aptitude
  apt: update_cache=yes
  tags:
    - zfs

- name: uninstall prior version of ZFS
  apt: name=zfs-fuse state=absent

- name: install and/or upgrade ZFS
  apt: name=debian-zfs state=latest
  tags:
    - zfs

- name: download glacier-cmd
  git: repo=https://github.com/uskudnik/amazon-glacier-cmd-interface.git dest=/usr/local/src/glacier-cmd

- name: install glacier-cmd
  command: python setup.py install
  args:
    chdir: /usr/local/src/glacier-cmd
