---
- name: install and/or upgrade core packages
  sudo: yes
  apt: name={{ item }} state=latest
  with_items:
    - gmetad
    - rrdtool
    - nginx
    - ufw

- name: Allow ports through firewall
  ufw: proto=tcp port={{ item }} rule=allow
  with_items:
    - 8649

- name: Synchronize node configuration
  template: src=gmond.conf dest=/etc/ganglia/gmond.conf
  notify:
    - restart gmond
