---
- name: install and/or upgrade core packages
  sudo: yes
  apt: name={{ item }} state=latest
  with_items:
    - ganglia-monitor
    - rrdtool
    - nginx
    - ufw

- name: Allow ports through firewall
  ufw: proto=tcp port={{ item }} rule=allow
  with_items:
    - 8649

- name: Synchronize node configuration
#  template: src={{ ganglia_conf }} dest=/etc/ganglia/gmond.conf
  template: src={{ ganglia_conf }} dest=/etc/ganglia/gmond.conf
  notify:
    - restart gmond
