---
- name: install ZFSonlinux repository
  get_url: url=http://archive.zfsonlinux.org/debian/pool/main/z/zfsonlinux/zfsonlinux_4_all.deb dest=/tmp/zfsonlinux.deb

- name: install ZFSonlinux repository
  sudo: yes
  command: dpkg -i /tmp/zfsonlinux.deb creates=/etc/apt/sources.list.d/zfsonlinux.list

- name: update aptitude
  sudo: yes
  apt: update_cache=yes

- name: install and/or upgrade core packages
  sudo: yes
  apt: name={{ item }} state=latest
  with_items:
    - tmux
    - debian-zfs
    - git
    - python-pip
    - postgresql-9.1
    - nagios3
    - nginx
    - php5-fpm
    - rrdtool

- name: download glacier-cmd
  sudo: yes
  git: repo=https://github.com/uskudnik/amazon-glacier-cmd-interface.git dest=/usr/local/src/glacier-cmd

- name: install glacier-cmd
  sudo: yes
  command: python setup.py install
  args:
    chdir: /usr/local/src/glacier-cmd

- name: delete the default nginx site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify:
    - reload nginx

- name: add the nginx base site
  copy: src=nginx.conf dest=/etc/nginx/sites-enabled/smisc
  notify:
    - reload nginx

- name: ensure permissions on webroot
  file: path=/usr/local/src/smisc state=directory owner=www-data mode=0555 recurse=yes
