---
- name: install base packages
  apt: name={{ item }} state=latest
  with_items: 
    - postgresql
    - php5-fpm
    - php5-pgsql
    - nginx
    - redis-server

- name: Synchronize nginx site configuration
  synchronize: src=config/nginx/sites-enabled/ dest=/etc/nginx/sites-enabled/
  notify: 
    - restart nginx

- name: Synchronize manager's initscript
  synchronize: src=config/initscripts/smisc-manager dest=/etc/init.d/smisc-manager

- name: Synchronize monit scripts
  synchronize: src=config/monit/ dest=/etc/monit/conf.d/
  notify:
     - reload monit

- name: Deploy smisc code
  synchronize: src=src/ dest=/usr/local/src/smisc/
  notify: 
    - restart manager

- name: Deploy smisc configuration
  synchronize: src=../../common/files/config/smisc.ini dest=/usr/local/share/smisc.ini
  notify:
    - restart manager

- name: Ensure manager is running
  service: name=smisc-manager state=started
