---
- name: install base packages
  sudo: yes
  apt: name={{ item }} state=latest
  with_items: 
    - postgresql
    - php5-fpm
    - php5-pgsql
    - nginx
    - redis-server

- name: Synchronize nginx site configuration
  sudo: yes
  synchronize: src=config/nginx/sites-enabled/ dest=/etc/nginx/sites-enabled/
  notify: 
    - restart nginx

- name: Synchronize manager's initscript
  sudo: yes
  synchronize: src=config/initscripts/smisc-manager dest=/etc/init.d/smisc-manager

- name: Synchronize monit scripts
  sudo: yes
  synchronize: src=config/monit/ dest=/etc/monit/conf.d/
  notify:
     - reload monit

