---
- name: temporarily disable monitoring
  command: monit unmonitor smisc-manager

- name: install base packages
  apt: name={{ item }} state=latest
  with_items: 
    - postgresql
    - php5-fpm
    - php5-pgsql
    - nginx
    - redis-server

- name: Synchronize nginx site configuration
  synchronize: src=config/nginx/sites-enabled/ dest=/etc/nginx/sites-enabled/
  notify: 
    - restart nginx

- name: Increase stock SHMMAX
  sysctl: name=kernel.shmmax value=8589934592 sysctl_set=yes

- name: Increase stock SHMALL
  sysctl: name=kernel.shmall value=2097152 sysctl_set=yes

- name: Synchronize PostgreSQL configuration
  synchronize: src=config/postgresql/ dest=/etc/postgresql/9.1/main/
  notify:
    - restart postgresql

- name: Synchronize redis configuration
  synchronize: src=config/redis/ dest=/etc/redis/
  notify:
    - restart redis

- name: Synchronize manager's initscript
  synchronize: src=config/initscripts/smisc-manager dest=/etc/init.d/smisc-manager

- name: Synchronize php-fpm config
  synchronize: src=config/php/{{ item }} dest=/etc/php5/fpm/{{ item }} archive=no
  with_items:
    - pool.d/www.conf
    - php.ini
    - php-fpm.conf
  notify:
    - restart php

- name: Synchronize monit scripts
  synchronize: src=config/monit/ dest=/etc/monit/ group=no owner=no perms=no recursive=yes
  notify:
     - restart monit

- name: Deploy smisc code
  synchronize: src=src/ dest=/usr/local/src/smisc/
  tags: 
    - hot
  notify: 
    - restart manager

- name: Synchronize phpPgAdmin
  synchronize: src=pgsql/ dest=/usr/share/nginx/sql group=no owner=no perms=no recursive=yes

- name: Add the pacsocial user to postgres
  sudo_user: postgres
  postgresql_user: name=pacsocial state=present

- name: Add the pacsocial database to postgres
  sudo_user: postgres
  postgresql_db: name=pacsocial state=present owner=pacsocial

- name: Deploy smisc configuration
  synchronize: src=../../common/files/config/smisc.ini dest=/usr/local/share/smisc.ini
  tags: 
    - hot
  notify:
    - restart manager

- name: Core services are running
  service: name={{ item }} state=started
  with_items:
    - postgresql
    - nginx
    - php5-fpm
    - smisc-manager
  tags:
    - hot

- name: re-enable monitoring
  command: monit monitor smisc-manager
