---
- name: set our hostname to smisc
  hostname: name={{ hostname }}

- name: set our hostname to smisc
  replace: dest=/etc/hostname regexp='(?!{{ fqdn }})' replace='{{ fqdn }}'

- name: set our FQDN
  lineinfile: create=yes state=present line="127.0.0.1 {{ fqdn }} {{ hostname }}" dest=/etc/hosts
  
- name: ensure local directory structure is set up
  command: mkdir -p "{{ item }}" creates={{ item }}
  with_items:
    - /var/local/log 
    - /var/local/run
    - /usr/local/share/nginx
    - /usr/local/src/{{ fqdn }}
    - /usr/local/src/{{ fqdn }}/dashboard
    - /usr/local/src/{{ fqdn }}/sql

- name: add base repositories
  apt_repository: repo='{{item}}' state=present
  with_items:
    - deb http://http.debian.net/debian wheezy main contrib non-free
    - deb-src http://http.debian.net/debian wheezy main contrib non-free

- name: install base packages
  apt: name={{ item }} state=latest
  with_items: 
    - ntp
    - vim
    - python3-pip
    - python-pip
    - build-essential
    - python-dev
    - python3-dev
    - monit
    - libpq-dev
    - htop
    - postgresql
    - php5-fpm
    - php5-pgsql
    - nginx
    - redis-server

- name: Install Python modules for 3-2
  pip: name={{ item }} executable=pip-3.2
  with_items:
    - TwitterAPI
    - redis
    - psycopg2

- name: Install Python modules for 2-7
  pip: name={{ item }} executable=pip-2.7
  with_items:
    - psycopg2


- name: Synchronize nginx configuration
  synchronize: src=config/nginx/ dest=/etc/nginx/ delete=yes
  notify: 
    - restart nginx
  tags:
    - nginx

- name: Increase stock SHMMAX
  sysctl: name=kernel.shmmax value=8589934592 sysctl_set=yes

- name: Increase stock SHMALL
  sysctl: name=kernel.shmall value=2097152 sysctl_set=yes

- name: Synchronize PostgreSQL configuration
  synchronize: src=config/postgresql/ dest=/etc/postgresql/9.1/main/
  notify:
    - restart postgresql

- name: Synchronize redis configuration
  synchronize: src=config/redis/ dest=/etc/redis/
  notify:
    - restart redis

- name: Synchronize binaries
  synchronize: src=config/bins/ dest=/usr/local/bin/ delete=no
  tags:
    - smisc

- name: Synchronize init scripst
  synchronize: src=config/initscripts/ dest=/etc/init.d/ delete=no
  tags:
    - smisc

# this changes every time. broken? archivce=no maybe it is changing permissions
#- name: Synchronize php-fpm config
#  synchronize: src=config/php/{{ item }} dest=/etc/php5/fpm/{{ item }} archive=no
#  with_items:
#    - pool.d/www.conf
#    - php.ini
#    - php-fpm.conf
#  notify:
#    - restart php

- name: Synchronize monit scripts
  synchronize: src=config/monit/ dest=/etc/monit/ group=no owner=no perms=no recursive=yes
  notify:
     - restart monit
  tags:
    - monit

- name: Ensure files have the proper mode and owner
  file: path={{ item.src }} owner={{ item.owner | default("root") }} mode={{ item.mode | default(0700) }}
  with_items:
    - { src: "/etc/monit/monitrc" }
    - { src: "/usr/local/share/nginx/{{ fqdn }}.crt", owner: "www-data", mode: 400 }
    - { src: "/usr/local/share/nginx/{{ fqdn }}.key", owner: "www-data", mode: 400 }
  tags:
    - monit

- name: Deploy smisc code
  synchronize: src=src/ dest=/usr/local/src/smisc/
  tags: 
    - smisc
    - hot

- name: Synchronize phpPgAdmin
  synchronize: src=pgsql/ dest=/usr/local/src/{{ fqdn }}/sql group=no owner=no perms=no recursive=yes
  tags:
    - smisc

- name: Synchronize dashboard code
  synchronize: src=dashboard/ dest=/usr/local/src/{{ fqdn }}/dashboard group=no owner=no perms=no recursive=yes
  tags:
    - smisc
    - hot

- name: Add the pacsocial user to postgres
  sudo_user: postgres
  postgresql_user: name=pacsocial state=present
  tags:
    - postgresql

- name: Add the pacsocial database to postgres
  sudo_user: postgres
  postgresql_db: name=pacsocial state=present owner=pacsocial
  tags:
    - postgresql

- name: Deploy smisc configuration
  synchronize: src=config/smisc.ini dest=/usr/local/share/smisc.ini
  tags: 
    - smisc
    - hot

- name: Core services are running
  service: name={{ item }} state=started
  with_items:
    - postgresql
    - nginx
    - php5-fpm
    - monit
  tags:
    - smisc
    - nginx
    - php
    - monit
    - postgresql
    - hot
