---
- name: Install packages
  sudo: yes
  tasks:
  - name: install base packages
    apt: name={{ item }} state=latest
    with_items: 
        - postgresql
        - php5-fpm
        - php5-pgsql
        - ntp
        - nginx
        - vim
        - python3-pip
        - python-pip
        - redis-server
        - monit

- name: Synchronize base configuration
  sudo: yes
  tasks:
  - name: sync nginx conf.d config
    synchronize: src=config/nginx/conf.d/ dest=/etc/nginx/conf.d/
    notify: 
        - restart nginx
  - name: sync nginx sites-enabled config
    synchronize: src=config/nginx/sites-enabled/ dest=/etc/nginx/sites-enabled/
    notify: 
        - restart nginx

- name: Install requisite Python modules
  sudo: yes
  tasks:
  - name: install python modules
    pip: name={{ item }}
    with_items:
        TwitterAPI
        redis
        psycopg2

- name: Deploy the latest version of the configuration and code
  sudo: yes
  tasks:
  - name: sync config
    synchronize: src=config/scraper.ini dest=/usr/local/share/scraper.ini
    notify:
      - restart scraper
  - name: sync code
    synchronize: src=src/ dest=/usr/local/src/smisc/
    notify: 
      - restart scraper
