#- name: temporarily disable monitoring
#  command: monit unmonitor smisc-scraper

- name: Synchronize initscript
  synchronize: src=config/initscripts/smisc-scraper dest=/etc/init.d/smisc-scraper

- name: Synchronize monit scripts
  synchronize: src=config/monit/ dest=/etc/monit/ group=no owner=no perms=no recursive=yes
  notify:
     - restart monit

- name: Deploy smisc code
  synchronize: src=src/ dest=/usr/local/src/smisc/
  tags: 
    - hot
  notify: 
    - restart scraper

- name: Deploy smisc configuration
  synchronize: src=../../common/files/config/smisc.ini dest=/usr/local/share/smisc.ini
  tags: 
    - hot
  notify:
    - restart scraper

- name: Ensure scraper is running
  service: name=smisc-scraper state=started
  tags: 
    - hot

- name: re-enable monitoring
  command: monit monitor smisc-scraper
