- name: Synchronize initscript
  synchronize: src=config/initscripts/smisc-scraper dest=/etc/init.d/smisc-scraper

- name: Deploy smisc code
  synchronize: src=src/ dest=/usr/local/src/smisc/
  notify: 
    - restart scraper

- name: Deploy smisc configuration
  synchronize: src=../../common/files/config/smisc.ini dest=/usr/local/share/smisc.ini
  notify:
    - restart scraper

- name: Ensure scraper is running
  service: name=smisc-scraper state=started
