---
- name: ensure local directory structure is set up
  command: mkdir -p "{{ item }}" creates={{ item }}
  with_items:
    - /var/local/log 
    - /var/local/run

- name: add base repositories
  apt_repository: repo='{{item}}' state=present
  with_items:
    - deb http://http.debian.net/debian wheezy main contrib non-free
    - deb-src http://http.debian.net/debian wheezy main contrib non-free

- name: install base packages
  apt: name={{ item }} state=latest
  with_items: 
    - ntp
    - vim
    - python3-pip
    - python-pip
    - build-essential
    - python-dev
    - python3-dev
    - monit
    - libpq-dev
    - htop

- name: Install Python modules
  pip: name={{ item }} executable=pip-3.2
  with_items:
    - TwitterAPI
    - redis
    - psycopg2

- name: Install Python modules for 2-7
  pip: name={{ item }} executable=pip-2.7
  with_items:
    - psycopg2

- name: Ensure files have the proper mode and owner
  file: path={{ item.src }} owner={{ item.owner | default("root") }} mode={{ item.mode | default(0700) }}
  with_items:
    - { src: "/etc/monit/monitrc" }

- name: Core services are running
  service: name={{ item }} state=started
  with_items:
    - monit
  tags:
    - hot
