---
- name: add base repositories
  sudo: yes
  apt_repository: repo='{{item}}' state=present
  with_items:
    - deb http://http.debian.net/debian wheezy main contrib non-free
    - deb-src http://http.debian.net/debian wheezy main contrib non-free

- name: install base packages
  sudo: yes
  apt: name={{ item }} state=latest
  with_items: 
    - ntp
    - vim
    - python3-pip
    - python-pip
    - build-essential
    - python-dev
    - python3-dev
    - monit

- name: Install Python modules
  sudo: yes
  pip: name={{ item }} executable=pip-3.2
  with_items:
    - TwitterAPI
    - redis
    - psycopg2

- name: Deploy smisc code
  sudo: yes
  synchronize: src=src/ dest=/usr/local/src/smisc/
  notify: 
    - restart scraper

- name: Deploy smisc configuration
  sudo: yes
  synchronize: src=config/smisc.ini dest=/usr/local/share/smisc.ini
  notify:
    - restart scraper

