---
- name: ensure local directory structure is set up
  command: mkdir -p "{{ item }}" creates={{ item }}
  with_items:
    - /var/local/log 
    - /var/local/run

- name: add base repositories
  apt_repository: repo='{{item}}' state=present
  with_items:
    - deb http://http.debian.net/debian wheezy main contrib non-free
    - deb-src http://http.debian.net/debian wheezy main contrib non-free

- name: install base packages
  apt: name={{ item }} state=latest
  with_items: 
    - ntp
    - vim
    - python3-pip
    - python-pip
    - build-essential
    - python-dev
    - python3-dev
    - monit
    - libpq-dev
    - htop

- name: Install Python modules
  pip: name={{ item }} executable=pip-3.2
  with_items:
    - TwitterAPI
    - redis
    - psycopg2

- name: Core services are running
  service: name={{ item }} state=started
  with_items:
    - monit
